openforcefield/openff-recharge

- devtools/conda-envs/test_env.yaml
- openff/recharge/grids/__init__.py
- openff/recharge/grids/grids.py
- openff/recharge/tests/grids/test_grids.py
This PR adds a simple grid generator (and accompanying settings class) which can currently generate FCC grids in shells around molecules.
> Initial Grid Generator Implementation

- openff/recharge/tests/utilities/test_utilities.py
- openff/recharge/utilities/__init__.py
- openff/recharge/utilities/utilities.py
This PR adds a new context manager `temporary_cd` which will temporarily change the working directory to either a specified directory or a temporary directory.
> Add Temporary Change Directory Context Manager

- openff/recharge/grids/grids.py
- openff/recharge/tests/grids/test_grids.py
This PR optimises the `GridGenerator` by allowing it to generate a rectangular, rather than cubic grid. This PR now also correctly converts the grid spacing into a lattice constant.
> Generate Lattice Grid Inside Rectangular Box

- devtools/conda-envs/test_env.yaml
- openff/recharge/data/psi4/input.dat
- openff/recharge/esp/exceptions.py
- openff/recharge/esp/psi4.py
- openff/recharge/tests/esp/test_psi4.py
This PR implements a new `Psi4ESPGenerator` object which uses the `psi4` package to generate electrostatic potentials.
> Add a Psi4 Implementation for Computing Electrostatic Potentials

- openff/recharge/charges/charges.py
This PR exposed the options to both optimize the conformer geometries and symmetrize the partial charges during an AM1 calculation.
> Expose the AM1 Optimize and Symmetrize Options

- openff/recharge/tests/charges/test_bcc.py
- scripts/validation/validate-nci.py
This PR moves the OE parity checks from the unit tests into a standalone, move comprehensive script.
> Move the Parity Checks to a Script

- devtools/conda-envs/test_env.yaml
- openff/recharge/esp/esp.py
- openff/recharge/esp/storage/__init__.py
- openff/recharge/esp/storage/db.py
- openff/recharge/esp/storage/storage.py
- openff/recharge/tests/esp/test_storage.py
- openff/recharge/utilities/pydantic.py
- setup.cfg
This PR adds a simple, lightweight store (based upon SQLite and SQLAlchemy) for calculated ESP data.
> Add SQLite Store for Calculated ESP Data

- openff/recharge/tests/utilities/test_geometry.py
- openff/recharge/utilities/geometry.py
This PR adds a simple utility to compute the inverse distance between to arrays of points.
> Add Inverse Distance Matrix Utility

- devtools/conda-envs/test_env.yaml
This PR slightly cleans up `test_env.yaml` by sectioning the dependencies.
> Order Conda Test Env Dependencies into Sections

- openff/recharge/data/psi4/input.dat
- openff/recharge/esp/__init__.py
- openff/recharge/esp/esp.py
- openff/recharge/esp/psi4.py
- openff/recharge/esp/storage/db.py
- openff/recharge/esp/storage/storage.py
- openff/recharge/tests/esp/test_psi4.py
- openff/recharge/tests/esp/test_storage.py
This PR adds support for including a polarisable continuum model (PCM) when computing and storing ESP grids.
> Adds PCM support for ESP calculations.

- openff/recharge/esp/esp.py
This PR adds validation to the PCM settings to ensure that the PCM cavity area is positive.
> Validate PCM Cavity Area is Positive

- openff/recharge/data/psi4/input.dat
- openff/recharge/esp/__init__.py
- openff/recharge/esp/esp.py
- openff/recharge/esp/psi4.py
- openff/recharge/esp/storage/db.py
- openff/recharge/tests/esp/test_psi4.py
- scripts/pytorch/optimize.py
This PR exposed an option to control the:
```
dft_spherical_points XXX
dft_radial_points XXX
dft_pruning_scheme XXX
```
inputs. In certain cases it is neccessary to use a finer DFT grid than default to [avoid SCF convergence issues](http://forum.psicode.org/t/dft-scf-not-converging/1725/4).
> Expose an Option to Control the PSI4 DFT Grid

- openff/recharge/esp/storage/db.py
- openff/recharge/esp/storage/storage.py
- openff/recharge/tests/esp/test_storage.py
This PR adds simple dictionary based provenance to ESP stores. This provenance is exposed via properties.
> Basic ESP Store Provenance

- .github/workflows/ci.yaml
This PR attempts to fix the recent CI failures due to a version parsing error related to the `gau2grid` package.
> Pin gau2grid to Resolve QCF CI Failures

- .github/workflows/ci.yaml
- README.md
- devtools/conda-envs/test_env.yaml
- openff/recharge/smirnoff/smirnoff.py
- openff/recharge/tests/smirnoff/test_smirnoff.py
- openff/recharge/utilities/exceptions.py
- setup.cfg
This PR migrates the package to use the new `openff-toolkit` package.
> Migrate to OpenFF Toolkit

- .github/workflows/ci.yaml
- .github/workflows/lint.yaml
- devtools/conda-envs/test_env.yaml
- openff/recharge/tests/conftest.py
- openff/recharge/tests/esp/test_qcarchive.py
This PR updates the CI to use the latest dependencies and ensures tests pass.
> Update CI versions and pin h5py

- openff/recharge/tests/utilities/test_geometry.py
- openff/recharge/tests/utilities/test_tensors.py
- openff/recharge/utilities/geometry.py
- openff/recharge/utilities/tensors.py
- setup.cfg
This PR abstracts common tensor operations, namely geometry calculations, that are executed differently using numpy and PyTorch backends into a single utility module with a consistent API.
> Abstract tensor operations into new utility

- openff/recharge/optimize/_optimize.py
- openff/recharge/tests/optimize/test_optimize.py
This PR fixes a critical bug whereby the ordering of the parameter assignment matrices did not match the ordering of the keys provided to `compute_objective_terms` and hence opened the possibility that they did not properly align with the vector of parameters to train in all cases.
> Fix optimization term matrix ordering

- devtools/conda-envs/test-env.yaml
- openff/recharge/esp/qcresults.py
- setup.cfg
This PR removes the accidental `cmiles` dependency that should have been removed in #97.
> Drop `cmiles` dependency

- openff/recharge/tests/utilities/test_toolkits.py
- openff/recharge/utilities/toolkits.py
This PR adds utilities for detecting topologically symmetrical atoms, and for tagging SMILES with possible duplicate atom indices.
> Add symmetry and SMILES tagging utilities

- openff/recharge/charges/library.py
- openff/recharge/tests/charges/test_library.py
This PR adds basic support for library charge parameters that contain duplicate atom indices, indicating that certain atoms in a molecule are equivalent.
> Support library charges with duplicate indices

- openff/recharge/charges/resp/_resp.py
This PR fixes a bug whereby stereochemical information wasn't included correctly in the RESP parameter SMILES, which in turn leads to the library charge parameter not matching the molecule it was created from.
> Fix stereochemistry dropped by RESP parameter

- openff/recharge/data/psi4/input.dat
- openff/recharge/esp/_esp.py
- openff/recharge/esp/psi4.py
- openff/recharge/tests/esp/test_psi4.py
This PR exposes options on `ESPGenerator` classes that allow users to request ESP, field, both or neither to be generated.
> Add option to not generate ESP / electric field

- .github/workflows/ci.yaml
- devtools/conda-envs/test-env.yaml
- openff/recharge/charges/qc.py
- openff/recharge/tests/charges/test_qc.py
This PR adds support for computing XTB base charges.
> Add support for XTB charges

- devtools/conda-envs/test-env.yaml
- openff/recharge/charges/vsite.py
- openff/recharge/optimize/_optimize.py
- openff/recharge/tests/charges/test_vsite.py
- openff/recharge/tests/optimize/test_optimize.py
This PR updates the framework to make use of the refactored toolkit v-site code introduced in 0.10.5
> Update to OpenFF Toolkit 0.10.5

- openff/recharge/charges/vsite.py
- openff/recharge/tests/charges/test_vsite.py
This PR fixes an exception raised when generating positions for multiple v-sites.
> Fix generating position of multiple v-sites

- .github/workflows/ci.yaml
- .gitignore
- devtools/conda-envs/test-env.yaml
Prior to #122, this PR aims to get tests passing using the old toolkit API.
> Add upper constraint on toolkit

- openff/recharge/tests/charges/test_bcc.py
Gosh, I wonder who is responsible for this one.
> Update a test for Interchange changes

- docs/index.md
- docs/releasehistory.md
* Add a release history
* Finalize 0.5.0 (with minimal notes)
Notable points that this PR has either accomplished or will accomplish.
> Finalize 0.5.0 release

- devtools/conda-envs/test_env_rdkit.yaml
- devtools/conda-envs/test_env_rdkit_and_openeye.yaml
Provide a brief description of the PR's purpose here.
Notable points that this PR has either accomplished or will accomplish.
> Pin CI to legacy QCFractal

- .github/workflows/ci.yaml
- openff/recharge/_pydantic.py
- openff/recharge/charges/bcc.py
- openff/recharge/charges/library.py
- openff/recharge/charges/qc.py
- openff/recharge/charges/vsite.py
- openff/recharge/conformers/_conformers.py
- openff/recharge/esp/_esp.py
- openff/recharge/esp/qcresults.py
- openff/recharge/esp/storage/_storage.py
- openff/recharge/grids/_grids.py
- openff/recharge/tests/charges/test_library.py
- openff/recharge/utilities/pydantic.py
- setup.cfg
This PR adds the common v1/v2 import guards so that Pydantic v2 (or v1) can be installed while still using v1 code.
> Stage Pydantic v2 compatibility

- docs/releasehistory.md
This PR adds release notes for 0.5.1 and serves as a final staging ground.
Notable points that this PR has either accomplished or will accomplish.
> Stage 0.5.1 release

- openff/recharge/_tests/esp/test_qcresults.py
- openff/recharge/esp/qcresults.py
Fixes #157
This PR checks for "pcm" in the keys of what was formerly the KeywordSet, and adds tests.
> Update qcportal results with solvent
