openforcefield/openff-recharge

- openff/recharge/tests/utilities/test_openeye.py
- openff/recharge/utilities/openeye.py
This PR adds a new `molecule_to_conformers` utility which extracts a molecules conformers and stores them in `numpy` arrays.
> Add a Utility to Extract a Molecules Conformers

- openff/recharge/esp/__init__.py
- openff/recharge/esp/esp.py
- openff/recharge/generators/bcc.py
- openff/recharge/generators/exceptions.py
- openff/recharge/tests/charging/test_bcc.py
- openff/recharge/tests/esp/test_esp.py
- openff/recharge/utilities/exceptions.py
This PR adds the base classes for those classes which will compute the electrostatic potentials (ESPs) of molecules using a specific frameworks (e.g. Psi4).
> Add Electrostatic Potential Base Classes

- .github/workflows/ci.yaml
This PR updates the CI to install the package using `setup.py` instead of `pip` before the tests are run. This is change is made in attempt to fix `codecov`.
> Install the CI package using setup.py instead of Pip

- openff/recharge/tests/utilities/test_openeye.py
- openff/recharge/utilities/openeye.py
This PR adds a new `guess_stereochemistry` option to the `smiles_to_molecule` which will attempt to generate, and then choose one of, the different stereoisomers of a molecule when the stereochemistry was not fully defined by the SMILES pattern.
> Guess Stereochemistry from SMILES

- openff/recharge/charges/bcc.py
- openff/recharge/tests/charges/test_bcc.py
This PR adds a new utility function which will compare whether the internal and OpenEye AM1BCC implementations are in agreement.
> Add AM1BCC Validation Utility

- openff/recharge/charges/bcc.py
- openff/recharge/tests/charges/test_bcc.py
This PR fixes a bug whereby the smirks patterns to detect cases two and three of the model made use of the `r` atom attribute to detect atoms in a six membered ring. This failed however for atoms which are in both six and five member rings and the `r` attribute only detects the size of the smallest ring.
> Fix AM1BCC Aromaticity Model for Acenaphthene

- openff/recharge/charges/bcc.py
- openff/recharge/tests/charges/test_bcc.py
This PR fixes edge cases in the AM1BCC aromaticity model whereby cases 2) and 3) should be applied self consistently to ensure that the aromaticity checks properly propagate down chained fused aromatic rings such as in the case of 2,7-Dimethylanthracene:
> Fix AM1BCC Aromaticity for Fused Aromatic Rings

- openff/recharge/esp/esp.py
- openff/recharge/tests/esp/test_esp.py
- openff/recharge/tests/esp/test_psi4.py
- openff/recharge/utilities/exceptions.py
This PR attempts to make the syntax of the `ESPGenerator.generator` function more unified with other similar methods by accepting a conformer as an argument rather than trying to read it off the input molecule.
> Standardise Syntax of ESPGenerator

- setup.cfg
This PR excludes lines from the codecov report which aren't expected to be tested, for example the type checking statements.
> Exclude Lines from Codecov Which Shouldn't be Tested

- openff/recharge/charges/bcc.py
This PR generalises the `BCCGenerator.applied_corrections` to accept a list of molecules rather than the assignment matrix, and to return back all of the BCC parameters which will be applied to these molecules.
> Generalise `BCCGenerator.applied_corrections`

- openff/recharge/tests/utilities/test_geometry.py
- openff/recharge/utilities/geometry.py
This PR adds a utility to re-order a molecules conformer to match the new atom ordering, whereby the old ordering is stored in a tagged smiles pattern.
> Adds Utility to Re-order Geometry to Match a Tagged Molecule

- openff/recharge/charges/bcc.py
- openff/recharge/optimize/optimize.py
- openff/recharge/tests/charges/test_bcc.py
- openff/recharge/tests/optimize/test_optimize.py
- scripts/convert-am1-bcc/convert.py
- scripts/pytorch/optimize.py
- scripts/validation/validate.py
This PR renames `BondChargeCorrection` to `BCCParameter` and `BCCSettings` to `BCCCollection` to be more consistent with the naming styles of the rest of the repository, and to be more obvious as to what data they represent.
> Rename BCC Classes to be More Obvious and Consistent

- openff/recharge/charges/bcc.py
- openff/recharge/conformers/__init__.py
- openff/recharge/conformers/conformers.py
- openff/recharge/tests/conformers/test_conformers.py
- scripts/pytorch/generate_esp.py
This PR standardises the conformer generator such that there is now a single conformer generation factory which accepts a settings object.
> Standardise Conformer Generation to use Factory + Settings Pattern

- openff/recharge/esp/storage/db.py
- openff/recharge/esp/storage/exceptions.py
- openff/recharge/esp/storage/storage.py
- openff/recharge/tests/esp/test_storage.py
This PR replaces the decimal column type (which is not supported by SQLite) currently used in the ESP store with an integer representation of a float with the precision tied to a new DB version. This version gets automatically added to new ESP stores and is validated against the frameworks supported version.
> Replace Decimal Type in ESP Store with Float Stored as Int

- .github/workflows/ci.yaml
This PR attempts to fix the SEGFAULT occurring on OSX CI jobs by pinning to an older version of `psi4`.
> Fix Psi4 SEGFAULT on OSX CI

- openff/recharge/charges/bcc.py
- openff/recharge/tests/charges/test_bcc.py
This PR fixes a bug whereby the order of applied corrections returned by `BCCGenerator.applied_corrections` depended on the order of the passed molecules. This is problematic when attempting to create a `BCCCollection` containing only the subset of applied parameters as they would then be applied in a different order than the original set.
> Return Applied Corrections In Original Order

- openff/recharge/charges/bcc.py
- openff/recharge/charges/charges.py
- openff/recharge/conformers/conformers.py
- openff/recharge/esp/esp.py
- openff/recharge/esp/psi4.py
- openff/recharge/esp/storage/storage.py
- openff/recharge/grids/grids.py
- openff/recharge/optimize/optimize.py
- openff/recharge/tests/utilities/test_openeye.py
- openff/recharge/utilities/exceptions.py
- openff/recharge/utilities/geometry.py
- openff/recharge/utilities/openeye.py
This PR moves all OE imports into function bodies and adds a nice exception when OE is missing explaining how it can be installed. 
Although OE is still required to use the main functionalities of the library, this allows the core data models to be used and accessed without having OE installed.
> Make Package Importable Without OE Installed

- devtools/conda-envs/test_env.yaml
- openff/recharge/cli/__init__.py
- openff/recharge/cli/cli.py
- openff/recharge/cli/generate.py
- openff/recharge/tests/cli/conftest.py
- openff/recharge/tests/cli/test_generate.py
- setup.py
This PR adds a new `recharge generate [OPTIONS] COMMAND [ARGS]` CLI command to generate ESP data for a set of smiles patterns based on settings defined in an `ESPSettings` JSON file and a `ConformerSettings` JSON file.
```
% recharge --help
Usage: recharge [OPTIONS] COMMAND [ARGS]...
Options:
--help  Show this message and exit.
Commands:
generate  Generate electrostatic property data for a set of SMILES.
% recharge generate --help
Usage: recharge generate [OPTIONS]
Generate electrostatic property data for a set of SMILES.
Options:
--smiles FILE         The path to a JSON file containing the set of SMILES
patterns.  [default: smiles.json]
--esp-settings FILE   The path to the JSON serialized ESP calculation
settings.  [default: esp-settings.json]
--conf-settings FILE  The path to the JSON …
```
> Add a CLI to Generate ESP from Schema Settings

- setup.py
This PR adds the core dependencies to `setup.py` so that the base package (namely the data models) can be installed and used directly from `pip`.
> Adds Core Dependencies to Setup

- openff/recharge/cli/generate.py
- openff/recharge/tests/cli/test_generate.py
This PR ensures that exceptions thrown by either the conformer generator or PSI4 are now correctly caught and reported without crashing the thread.
Results are now also stored when ready so as to avoid having to redo entire computations if something does go wrong and isn't caught.
> Catch Generate CLI Exceptions

- openff/recharge/smirnoff/smirnoff.py
- openff/recharge/tests/utilities/test_utilities.py
- openff/recharge/utilities/__init__.py
- openff/recharge/utilities/utilities.py
This PR adds a new `requires_package` decorator which raises a `MissingOptionalDependency` error when the required package is not found when calling the decorated function.
> Add a Requires Package Utility Decorator

- openff/recharge/esp/storage/db.py
This PR is an addition to #53 to ensure that 'orphaned' provenance information (i.e. entries which have been removed from the provenance dictionary) are automatically removed from the database.
> Automatically Remove Orphaned Provenance

- openff/recharge/smirnoff/smirnoff.py
- openff/recharge/tests/smirnoff/test_smirnoff.py
This PR adds support for SMIRNOFF BCCs where the reverse charge to apply is implicitly defined (see https://github.com/openforcefield/openff-toolkit/pull/726).
> Support SMIRNOFF BCCs with Implicit Reverse Value

- .github/workflows/ci.yaml
- devtools/conda-envs/test_env.yaml
This PR unpins the `gau2grid` package in the test environment as it seems to be causing the dependencies to be unresolvable on OSX, and instead only pins on Linux where the pin is needed.
> Revert gau2grid Pin

- .github/workflows/ci.yaml
- devtools/conda-envs/test-psi4.yaml
- devtools/conda-envs/test-torch.yaml
- devtools/conda-envs/test_env.yaml
- openff/recharge/charges/vsite.py
- openff/recharge/tests/charges/test_vsite.py
- openff/recharge/tests/esp/test_qcarchive.py
This PR adds an automatically differentiable, fully vectorised way (`VirtualSiteGenerator.convert_local_coordinates`) to compute the positions of virtual sites.
This PR will be followed by another that will add utilities to train the geometry (i.e. distance, in plane and out of plane angles) parameters of virtual sites alongside their charge increments.
@mattwthompson this may be of interest to you as you start to consider matrix representations of v-sites in `openff-interchange`.
> Add 'autodiff-able' function to compute v-site positions

- openff/recharge/charges/bcc.py
- openff/recharge/charges/vsite.py
- openff/recharge/tests/charges/test_bcc.py
- openff/recharge/tests/charges/test_vsite.py
This PR adds convience methods to easily 'vectorize' BCC and virtual site collections into flat parameter vectors that can be easily used for training.
> Add convenience methods to vectorize collections

- openff/recharge/charges/vsite.py
- openff/recharge/optimize/__init__.py
- openff/recharge/optimize/optimize.py
- openff/recharge/tests/optimize/test_optimize.py
- openff/recharge/tests/utilities/test_tensors.py
- openff/recharge/utilities/tensors.py
This PR extends #63 to allow the local frame coordinates (e.g. their distance, in-plane and out-of-plane angles) to be optimised alongside the charge increment parameters.
This PR will temporarily break the examples in the `scripts folder`. These will be split into a new directory and cleaned up in a separate PR however and so will not be updated here to stop this PR from growing too large.
> Add support for optimizing v-site coordinates

- openff/recharge/optimize/optimize.py
- openff/recharge/tests/optimize/test_optimize.py
- openff/recharge/tests/utilities/test_tensors.py
- openff/recharge/utilities/tensors.py
This PR adds an experimental method for combining multiple objective terms into a single object containing almost fully vectorised arrays.
The only part of the loss function evaluation that is not vectorised is computing the pairwise distances between the virtual sites and the grid points.
> Add helper method to combine objective terms

- examples/parameter-training/pytorch/train-parameters.py
- openff/recharge/optimize/optimize.py
- openff/recharge/tests/optimize/test_optimize.py
This PR splits the `ObjectiveTerm.evaluate` function into a `predict` and `loss` function to make using custom loss functions easier.
> Split `evaluate` term into `predict` and `loss`

- examples/parameter-training/pyro/train-parameters.py
This PR adds an example of using `pyro` to sample a set of BCC and virtual site parameters from a posterier where the likelihood function penalises deviations between a reference set of electrostatic properties (e.g. ESP) and a set predicted using the current parameters.
cc @ocmadin @trevorgokey
> Add pyro example

- devtools/conda-envs/test-psi4.yaml
- devtools/conda-envs/test-torch.yaml
- examples/parameter-training/numpy/train-bcc-parameters.py
- openff/recharge/charges/vsite.py
- openff/recharge/tests/charges/test_vsite.py
- openff/recharge/tests/cli/test_reconstruct.py
- openff/recharge/tests/conftest.py
- openff/recharge/tests/esp/test_qcarchive.py
- openff/recharge/tests/optimize/test_optimize.py
This PR completely drops QC fractal snowflake which is completely unstable and constantly breaks and instead pulls directly from the main QCA. It also swaps from using an un-released version of the OpenFF toolkit to the latest release.
Virtual sites are completely broken until [a bug in the OpenFF toolkit](https://github.com/openforcefield/openff-toolkit/issues/1159) is fixed.
> Fix flaky QC tests and use released toolkit

- openff/recharge/esp/qcresults.py
- openff/recharge/esp/storage/_storage.py
- openff/recharge/tests/esp/test_qcresults.py
This PR fixes a bug where units would be attached to the electric field computed from electric field data even when it was `None`.
> Fix attaching units to `None` electric field from QCF

- openff/recharge/esp/qcresults.py
This PR fixes a bug when attempting to reconstruct the ESP around a molecule with 'undefined stereochemistry'.
> Fix from QC molecule with undefined stereo

- openff/recharge/charges/resp/_resp.py
- openff/recharge/tests/charges/resp/test_resp.py
This PR fixes generating the initial dummy set of charges for a RESP parameter that should sum to the expected total charge of the molecule.
> Fix generating dummy RESP initial charges

- CHANGELOG.md
- openff/recharge/optimize/_optimize.py
- openff/recharge/tests/optimize/test_optimize.py
This PR fixes exceptions raised where a training set contains molecules to which no v-sites being trained would be applied.
> Fix exception when objective term matches no v-sites

- devtools/conda-envs/docs-env.yaml
- devtools/conda-envs/test-env.yaml
- openff/recharge/utilities/toolkits.py
Sorry for the API break (it's just a deprecation, but I might as well fix it now)
> `MissingOptionalDependency` -> `MissingOptionalDependencyError`

- .gitignore
- docs/conf.py
- docs/getting-started/installation.md
Adds a link to the [ecosystem install guide](https://docs.openforcefield.org/en/latest/install.html) to the project install guide
> Add link to OpenFF install guide

- openff/recharge/charges/vsite.py
- openff/recharge/optimize/_optimize.py
- openff/recharge/tests/charges/test_vsite.py
- openff/recharge/tests/optimize/test_optimize.py
Fixes #136
Updates virtual site code to interact with OpenFF Interchange, as per post 0.11 OpenFF toolkit.
A lot of OpenFF recharge bookkeeping depends on the following structure for a key: `(parameter.smirks, parameter.type, parameter.name)`. I kept it in this refactor to get it running asap, but it's somewhat fragile -- the smirks is stored in a `PotentialKey` in interchange as part of `PotentialKey.id`. It's also likely to change in the future if the `TODO` is anything to go by. Just something to keep an eye out for.
https://github.com/openforcefield/openff-interchange/blob/main/openff/interchange/smirnoff/_virtual_sites.py#L107-L113
```
potential_key = PotentialKey(
id=" ".join(
[parameter.smirks, parameter.name, parameter.match],
),
associated_handler="VirtualSites",
)
```
> Update virtual sites to 0.11+

- openff/recharge/_tests/esp/test_psi4.py
- openff/recharge/esp/_esp.py
- openff/recharge/esp/psi4.py
#146
Notable points that this PR has either accomplished or will accomplish.
> Optionally generate Psi4 ESPs with multiple threads

- openff/recharge/_tests/esp/test_psi4.py
- openff/recharge/data/psi4/input.dat
- openff/recharge/esp/_esp.py
- openff/recharge/esp/psi4.py
Relates to #168 , #169 
This sets the memory usage in the input file. The other way is to use commandline (`psi4 --memory`), which I decided not to go with because:
* it's more difficult to test
* it makes it easier to theoretically pass around input files as the memory requirements are encoded
> Add memory specification to file
